config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations'}
  root to: 'users#index'
  get 'inform/view'
  get 'inform/add'
  get 'inform/create'
  get 'users/all'
  get 'users/index'
  delete 'users/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/progress.rb
class Progress < ApplicationRecord
  validates  :name, :surname, :activity, :result, presence: true, length: { minimum: 2, maximum: 30 }
  validates :classroom, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable
  validates :name, :surname, :key_role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inform_controller.rb
class InformController < ApplicationController
  before_action :authenticate_user!, only: [:add, :create]
  before_action :parse_params, only: :create
  before_action :select_class, only: [:add, :view]

  def view
    @records = Progress.all
  end

  def add
    @res = ['Победитель', 'Призер', 'Участник']
  end

  def create
    res = Progress.find_by(parse_params)
    if res.nil?
      record = Progress.new(parse_params)
      if record.save
        respond_to do |format|
          format.html { redirect_to inform_add_path, notice: 'Новые данные добавлены' }
          #format.html { render :add, notice: 'Successfully create new record'}
          format.json { render json: record.to_json}
        end
      else 
        respond_to do |format|
          format.html { redirect_to inform_add_path, notice:'Поля заполнены неправильно' }
          format.json { render json: 'invalid data'}
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to inform_add_path, notice:'Данная запись уже существует' }
        format.json { render json: 'invalid data'}
      end
    end
  end 

  private

  def parse_params
    hash = {name: params[:name], surname: params[:surname], classroom: params[:classroom], activity: params[:activity], result: params[:result]}
  end

  def select_class
    @classes = [1,2,3,4,5,6,7,8,9,10,11]
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    @user = User.new(parse_params)
    if @user.save
      respond_to do |format|
        format.html { redirect_to new_user_session_path, notice: 'Пользователь успешно создан'}
      end
    else
      respond_to do |format|
        format.html { redirect_to new_user_registration_path, notice: 'Пользователь не создан. Ошибка ввода'}
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   @user = current_user.update(update_params)
  #   if @user
  #     respond_to do |format|
  #       format.html { redirect_to root_url, notice: 'Аккаунт успешно обновлен'}
  #     end
  #   else
  #     respond_to do |format|
  #       format.html { redirect_to edit_user_registration_path, notice: 'Аккаунт не обновлен'}
  #     end
  #   end
  # end

  # DELETE /resource
  # def destroy
  # 
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :middlename, :current_user, :password, :password_confirmation])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private
    def parse_params
      params.require(:user).permit(:name, :surname, :email, :password, :key_role, :password_confirmation)
    end

    # def update_params
    #   params.require(:user).permit(:name, :surname, :middlename,:email, :key_role, :password, :password_confirmation)
    # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def all
    @users = User.all
  end

  def index
    if current_user.nil?
      redirect_to inform_view_path
    elsif current_user.key_role == 'student' 
      @student = Progress.where(name: current_user.name, surname: current_user.surname)
    end
  end

  def destroy 
    p @user = User.find_by_id(params[:id])
    @user.delete
    respond_to do |format|
      format.html { redirect_to users_all_url, notice: 'User was successfully destroyed'}
      format.json { render json: 'user destroyed'}
      format.js  
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inform_helper.rb
module InformHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inform/add.html.erb
<div class="d-flex flex-column flex-md-row align-items-center px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h4 class="my-0 mr-md-auto font-weight-normal"><%= t :inform_add %></h4>
  <nav class='my-2 my-md-0 mr-md-3' >
    <div class='row'>
      <p class='h5 p-2 text-dark'><%= link_to t(:Progress), inform_view_path, method: :get, class: 'badge badge-primary' %></p>
      <p class='h5 p-2 text-dark'><%= link_to t(:Account), root_url, method: :get, class: 'badge badge-primary' %></p>
    </div>
  </nav>  
</div>
  <%= form_tag url_for(controller: :inform, action: :create), method: 'get' do %>
      <div class="form-group col-5">
        <%= label_tag :name, t(:name) %>
        <%= text_field_tag :name, nil, class: "form-control" %>
      </div>
      <div class="form-group col-5">
        <%= label_tag :surname, t(:surname) %>
        <%= text_field_tag :surname, nil, class: "form-control"%>
      </div>
      <div class="form-group col-5">
        <%= label_tag :classroom, t(:classroom) %>
        <%= select_tag :classroom, options_for_select(@classes), class: 'offset-1' %>
      </div>
      <div class="form-group col-5">
        <%= label_tag :activity, t(:activity) %>
        <%= text_field_tag :activity, nil, class: "form-control" %>
      </div>
      <div class="form-group col-5">
        <%= label_tag :result, t(:result) %>
        <%= select_tag :result, options_for_select(@res), class: 'offset-1' %>
      </div>
      <div class="form-group col-5">
        <%= submit_tag 'Добавить', class: "btn btn-primary" %>
      </div>
  <% end %>   

app/views/inform/view.html.erb
<div class="d-flex flex-column flex-md-row align-items-center px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h4 class="my-0 mr-md-auto font-weight-normal"><%= t :inform_view %></h4>
  <nav class='my-2 my-md-0 mr-md-3' >
    <div class='row'>
      <% if user_signed_in? %>
        <p class='h5 p-2 text-dark'><%= link_to t(:Account), root_url, method: :get, class: 'badge badge-primary' %></p>
      <% else %>
        <p class='h5 p-2 text-dark'><%= link_to t(:Authentication), new_user_session_path, method: :get, class: 'badge badge-primary' %></p>
      <% end %>
    </div>
  </nav>  
</div>
<div class='container'> 
  <h4 class='text-center'>Достижения учеников школы</h4>
  <% unless @records.empty? %>
  <table class='table table-bordered table-hover'>
    <thead>
      <th><div class='col-1'></div></th>
      <th>Имя</th>
      <th>Фамилия</th>
      <th>Класс</th>
      <th>Мероприятие</th>
      <th>Достижение</th>
    </thead>
    <tbody>
      <% @records.each do |elem| %>
        <tr>
          <th><%= elem.id %></th>
          <td><%= elem.name %></td>
          <td><%= elem.surname %></td>
          <td><%= elem.classroom %></td>
          <td><%= elem.activity %></td>
          <td><%= elem.result %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
  <% else %>
    <%= 'Database is empty' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Participant</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/all.html.erb
<div class="d-flex flex-column flex-md-row align-items-center px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h4 class="my-0 mr-md-auto font-weight-normal"><%= t :user_account %></h4>
  <nav class='my-2 my-md-0 mr-md-3' >
    <div class='row'>
      <p class='p-2 text-dark'><%= link_to 'Достижения', inform_view_path, method: :get %></p>
      <p class='p-2 text-dark'><%= link_to 'Добавить', inform_add_path, method: :get %></p>
      <p class='p-2 text-dark'><%= link_to 'Выйти', destroy_user_session_path, method: :delete %></p>
    </div>
  </nav>  
</div>
<div class='container'>
  <% unless @users.empty? %> 
  <h4 class='text-center'>Зарегистрированные пользователи</h4>
    <table class='table table-bordered table-hover'>
      <thead>
        <th>Пользователь</th>
        <th>Почта</th>
        <th>Тип аккаунта</th>
        <th></th>
      </thead>
      <tbody class='table-hover'>
        <% @users.each do |user| %>
          <% unless user.key_role == 'admin' %>
            <tr id='<%= user.id %>'>
            <td><%= user.name + ' ' + user.surname %></td>
            <td><%= user.email %></td>
            <td><%= user.key_role %></td>   
            <td><%= link_to 'Удалить', users_destroy_path(id: user.id), method: :delete, remote: true, class: 'delete_user' %> </td>     
            </tr>
          <% end %>  
        <% end %>          
      </tbody>
    </table>
  <% else %>
    <%= 'Database is empty' %>
  <% end %>
</div>

app/views/users/destroy.js.erb
document.getElementById('<%= @user.id %>').remove()

app/views/users/edit.html.erb
<div class="d-flex flex-column flex-md-row align-items-center px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h4 class="my-0 mr-md-auto font-weight-normal"><%= t :edit_user_registration %></h4>
    <nav class='my-2 my-md-0 mr-md-3' >
      <div class='row'>
        <p class='p-2 text-dark'><%= link_to 'Назад', :back %></p>
      </div>
    </nav>  
  </div>

<div class='container'>
  <%= form_for @user, url: users_update_path do |f| %>
  
    <div class='container'>
      <div class='row form-group'>
        <div class='col-2'><%= f.label :name, t(:name) %></div>
        <div class='col-5'><%= f.text_field :name, autofocus: true, autocomplete: "name" %></div>
      </div>
      <div class='row form-group'>
        <div class='col-2'><%= f.label :surname, t(:surname) %></div>
        <div class='col-5'><%= f.text_field :surname, autocomplete: "surname" %></div>
      </div>
      <div class='row form-group'>
        <div class='col-2'><%= f.label :middlename, t(:middlename) %></div>
        <div class='col-5'><%= f.text_field :middlename, autocomplete: "middlename" %></div>
      </div>
      <!--For updating email 
      <div class='row form-group'>
        <div class='col-2'><%= f.label :email, t(:email) %></div>
        <div class='col-5'><%= f.email_field :email, autocomplete: "email" %></div>
      </div> -->
      <div class='row form-group'>
        <div class='col-2'><%= f.label :current_password, t(:current_password) %></div>
        <div class='col-5'><%= f.password_field :current_password, autocomplete: "current-password" %></div>
      </div>
      <div class='row form-group'>
        <div class='col-2'><%= f.label :password, t(:password) %></div>
        <div class='col-5'><%= f.password_field :password, autocomplete: "new-password", placeholder: "leave blank to don't change it" %></div>
      </div>
      <div class='row form-group'>
        <div class='col-2'><%= f.label :password_confirmation t(:password_confirmation) %></div>
        <div class='col-5'><%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "leave blank to don't change it" %></div>
      </div>
      <div class="actions">
        <%= f.submit t(:Update), class: 'btn btn-primary' %>
      </div>
    </div>
  
  <% end %>
</div>

app/views/users/index.html.erb
<div class="d-flex flex-column flex-md-row align-items-center px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h4 class="my-0 mr-md-auto font-weight-normal"><%= t :user_account %></h4>
  <nav class='my-2 my-md-0 mr-md-3' >
    <div class='row'>
    <% if current_user.key_role == 'teacher' %>
      <p class='h5 p-2 text-dark'><%= link_to t(:Progress), inform_view_path, method: :get, class: 'badge badge-primary' %></p>
      <p class='h5 p-2 text-dark'><%= link_to t(:Add), inform_add_path, method: :get, class: 'badge badge-primary' %></p>
      <p class='h5 p-2 text-dark'><%= link_to t(:Exit), destroy_user_session_path, method: :delete, class: 'badge badge-primary' %></p>
    <% elsif current_user.key_role == 'student' %>
      <p class='h5 p-2 text-dark'><%= link_to t(:Exit), destroy_user_session_path, method: :delete, class: 'badge badge-primary' %></p>
    <% else %>
      <p class='h5 p-2 text-dark'><%= link_to t(:Users), users_all_path, method: :get, class: 'badge badge-primary' %></p> 
      <p class='h5 p-2 text-dark'><%= link_to t(:Exit), destroy_user_session_path, method: :delete, class: 'badge badge-primary' %></p>   
    <% end %>
    </div>
  </nav>  
</div>
<div class='align-items-left col-5 offset-1'>
  <div class='row'><p>Пользователь:         <%= current_user.name + " " + current_user.surname %></p></div>
  <div class='row'><p>Тип аккаунта: <%= current_user.key_role %></div>
  <div class='row'><p>Почта:        <%= current_user.email %></div>
  <div class='row'>
    <%= link_to t(:Update_profile), edit_user_registration_path, method: :get %>
  </div>
</div><br/>
<div class='container col-7 align-items-center'>

  <% if current_user.key_role == 'student'%>
  <h4 class='-b-1 text-center'>Личные достижения</h4>
    <table class='table table-bordered table-hover'>
      <thead>
        <th><div class='col-1'></div></th>
        <th>Мероприятие</th>
        <th>Достижение</th>
      </thead>
      <tbody>
          <% @student.each do |row| %>
            <tr>
              <th style='width: 20px'><%= row.id %></th>
              <td><%= row.activity %></td>
              <td><%= row.result %></td>
            </tr>
          <% end %>          
      </tbody>
    </table>
  <% end %>
</div>